"""alter status and exact_amount to index in PaymentIntent

Revision ID: 2eb332f15e16
Revises: 6027b808a41b
Create Date: 2026-06-10 20:57:29.525905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb332f15e16'
down_revision: Union[str, Sequence[str], None] = '6027b808a41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_intent_exact_amount'), 'payment_intent', ['exact_amount'], unique=False)
    op.create_index(op.f('ix_payment_intent_status'), 'payment_intent', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_intent_status'), table_name='payment_intent')
    op.drop_index(op.f('ix_payment_intent_exact_amount'), table_name='payment_intent')
    # ### end Alembic commands ###
