"""add payment_intent table

Revision ID: 35020614cb8c
Revises: fa6baf2dbacd
Create Date: 2026-06-06 12:35:16.412595

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = "35020614cb8c"
down_revision: Union[str, Sequence[str], None] = "fa6baf2dbacd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_intent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            PG_ENUM(
                "PENDING",
                "REVIEWED",
                "PAID",
                "FAILED",
                "EXPIRED",
                name="orderstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("base_amount", sa.Integer(), nullable=False),
        sa.Column("exact_amount", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exact_amount"),
    )
    op.create_index(
        "idx_pending_price",
        "payment_intent",
        ["exact_amount"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        op.f("ix_payment_intent_order_id"), "payment_intent", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_intent_order_id"), table_name="payment_intent")
    op.drop_index(
        "idx_pending_price",
        table_name="payment_intent",
        postgresql_where=sa.text("status == 'PENDING'"),
    )
    op.drop_table("payment_intent")
    # ### end Alembic commands ###
