"""change expired_at_test name

Revision ID: 409ca9bc0f2a
Revises: df6730679827
Create Date: 2026-06-06 21:24:36.084880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '409ca9bc0f2a'
down_revision: Union[str, Sequence[str], None] = 'df6730679827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '1 day'"), nullable=False))
    op.drop_column('payment_intent', 'expired_at_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at_test', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP + '1 day'::interval)"), autoincrement=False, nullable=False))
    op.drop_column('payment_intent', 'expired_at')
    # ### end Alembic commands ###
