"""alter sms_date and sms_time to string and set non-nullable

Revision ID: 6027b808a41b
Revises: af232a3eb761
Create Date: 2026-06-09 17:36:48.603745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6027b808a41b'
down_revision: Union[str, Sequence[str], None] = 'af232a3eb761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_transactions', 'sms_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('sms_transactions', 'sms_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_transactions', 'sms_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sms_transactions', 'sms_date',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
