"""make exact_amount non-unique globally

Revision ID: 8c191d5839c5
Revises: 1afa510335c3
Create Date: 2026-06-07 20:01:27.268115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c191d5839c5'
down_revision: Union[str, Sequence[str], None] = '1afa510335c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '1 day'"), nullable=False))
    op.drop_constraint(op.f('payment_intent_exact_amount_key'), 'payment_intent', type_='unique')
    op.drop_column('payment_intent', 'expired_at_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at_test', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP + '1 day'::interval)"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('payment_intent_exact_amount_key'), 'payment_intent', ['exact_amount'], postgresql_nulls_not_distinct=False)
    op.drop_column('payment_intent', 'expired_at')
    # ### end Alembic commands ###
