"""add smstransaction table

Revision ID: af232a3eb761
Revises: 8c191d5839c5
Create Date: 2026-06-09 17:28:16.153728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af232a3eb761'
down_revision: Union[str, Sequence[str], None] = '8c191d5839c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sms_amount', sa.Integer(), nullable=False),
    sa.Column('sms_inventory', sa.Integer(), nullable=False),
    sa.Column('sms_date', sa.DateTime(), nullable=False),
    sa.Column('sms_time', sa.DateTime(), nullable=False),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sms_amount', 'sms_inventory', 'sms_date', 'sms_time', name='uq_sms_amount_inventory_date_time')
    )
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('payment_intent_order_id_fkey'), 'payment_intent', type_='foreignkey')
    op.create_foreign_key(None, 'payment_intent', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_intent', type_='foreignkey')
    op.create_foreign_key(op.f('payment_intent_order_id_fkey'), 'payment_intent', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_table('sms_transactions')
    # ### end Alembic commands ###
