"""make telegram_id nullable and add hash_password

Revision ID: b574aa3538a0
Revises: 46f8631fcb3f
Create Date: 2026-05-20 19:42:29.199027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b574aa3538a0'
down_revision: Union[str, Sequence[str], None] = '46f8631fcb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    # ### end Alembic commands ###
