"""make expired_at server default uniform

Revision ID: df6730679827
Revises: 2bb11a17d8ff
Create Date: 2026-06-06 18:00:55.588066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df6730679827'
down_revision: Union[str, Sequence[str], None] = '2bb11a17d8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('payment_intent', 'expired_at_test')
    # ### end Alembic commands ###
