"""make expired_at server default uniform

Revision ID: e7b9bf2b2dec
Revises: 2bb11a17d8ff
Create Date: 2026-06-06 17:51:35.696887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b9bf2b2dec'
down_revision: Union[str, Sequence[str], None] = '2bb11a17d8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at_test', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '1 day'"), nullable=False))
    op.drop_column('payment_intent', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intent', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('payment_intent', 'expired_at_test')
    # ### end Alembic commands ###
