"""add family_id and relationship to refresh table

Revision ID: fa6baf2dbacd
Revises: f381e93df3d5
Create Date: 2026-05-23 18:59:05.604246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa6baf2dbacd'
down_revision: Union[str, Sequence[str], None] = 'f381e93df3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('refresh_tokens', sa.Column('family_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'family_id')
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
